// This file was generated by img2gb, DO NOT EDIT

#ifndef _BREAKOUT_TILEMAP_LEVEL01MAP_H
#define _BREAKOUT_TILEMAP_LEVEL01MAP_H

extern UINT8 TILEMAP[];
#define TILEMAP_WIDTH 20
#define TILEMAP_HEIGHT 18


#endif
