// This file was generated by img2gb, DO NOT EDIT

#ifndef _GAMEOVER_H
#define _GAMEOVER_H

extern UINT8 TILEMAP_GAMEOVER[];
#define TILEMAP_GAMEOVER_WIDTH 9
#define TILEMAP_GAMEOVER_HEIGHT 1


#endif
