// This file was generated by img2gb, DO NOT EDIT

#ifndef _PRESS_STARTMAP_H
#define _PRESS_STRATMAP_H

extern UINT8 TILEMAP_START[];
#define TILEMAP_START_WIDTH 11
#define TILEMAP_START_HEIGHT 1


#endif
