// This file was generated by img2gb, DO NOT EDIT

#ifndef _VICTORYMAP_H
#define _VICTORYMAP_H

extern UINT8 TILEMAP_VICTORY[];
#define TILEMAP_VICTORY_WIDTH 7
#define TILEMAP_VICTORY_HEIGHT 1


#endif
